/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GameTypeResponse {
  id?: number;
  typeName?: string;
  timeControl?: number;
}
