/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface GameResponse {
  id?: string;
  uciFen?: string;
  whitePlayer?: User;
  blackPlayer?: User;
  whiteElo?: number;
  blackElo?: number;
  whiteEloChange?: number;
  blackEloChange?: number;
  startTime?: string;
  endTime?: string;
  blackTimeLeft: number;
  whiteTimeLeft: number;
  result?: string;
  resultDetail?: string;
}
