/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserResponse {
  id: number;
  sub: string;
  email: string;
  displayName?: string;
  username?: string;
  picture?: string;
}
