/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface User {
  id?: number;
  sub?: string;
  email?: string;
  name?: string;
  username?: string;
  picture?: string;
}
